name: Docker Hub - CI

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: The tag to use for the Docker image.
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: tombailey256
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: docker build . -t tombailey256/checkpoint:${{ github.event.inputs.tag }}
      - name: Push the Docker image
        run: docker push tombailey256/checkpoint:${{ github.event.inputs.tag }}
